// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp5FJRVU5gxaZBKvYP0PlqHbB8F3rZnZI',
    appId: '1:936972321217:web:136c2f21504b68d3016f40',
    messagingSenderId: '936972321217',
    projectId: 'rentalmobil-9b8ad',
    authDomain: 'rentalmobil-9b8ad.firebaseapp.com',
    storageBucket: 'rentalmobil-9b8ad.appspot.com',
    measurementId: 'G-V18G1QTBX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjFs2JXHGKdtWc2hHW1v-sFzFVpQaqqMk',
    appId: '1:936972321217:android:37b161cbd0364ef8016f40',
    messagingSenderId: '936972321217',
    projectId: 'rentalmobil-9b8ad',
    storageBucket: 'rentalmobil-9b8ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp-izbOwilj_IqWIvYqEp_LQEajiOl6FI',
    appId: '1:936972321217:ios:930a9bb1bd5d365d016f40',
    messagingSenderId: '936972321217',
    projectId: 'rentalmobil-9b8ad',
    storageBucket: 'rentalmobil-9b8ad.appspot.com',
    iosBundleId: 'com.example.rentalMobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp-izbOwilj_IqWIvYqEp_LQEajiOl6FI',
    appId: '1:936972321217:ios:930a9bb1bd5d365d016f40',
    messagingSenderId: '936972321217',
    projectId: 'rentalmobil-9b8ad',
    storageBucket: 'rentalmobil-9b8ad.appspot.com',
    iosBundleId: 'com.example.rentalMobil',
  );
}
